"""migration

Revision ID: 61b759d1d31d
Revises: 960cc65dd7df
Create Date: 2026-02-27 11:53:35.138577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b759d1d31d'
down_revision: Union[str, Sequence[str], None] = '960cc65dd7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # DROP TABLE verification_tokens;
    op.drop_table("verification_tokens")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_tokens', type_='foreignkey')
    op.drop_column('verification_tokens', 'user_id')
    # ### end Alembic commands ###
